_commit: c727b07
_src_path: gh:jexxa-projects/clegmed-template
author_name: jexxa-projects
docker_registry: ghcr.io
project_name: clegmed-app
vcs_repository: https://github.com/jexxa-projects/clegmed-app
